In [11]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.1,7,1,0,0.5])

Implement Mean Absolute Error

In [12]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [13]:
mae(y_predicted, y_true)

Total error is: 10.6
Mean absolute error is: 2.12


2.12

implement same thing using numpy in much easier way

In [15]:
np.abs(y_predicted-y_true)

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [16]:
np.mean(np.abs(y_predicted-y_true))

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [17]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [18]:
mae_np(y_predicted, y_true)

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

Implement Log Loss or Binary Cross Entropy

In [19]:
np.log([0])

C:\Users\emon1\AppData\Local\Temp\ipykernel_9636\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [20]:
epsilon = 1e-15

In [21]:
np.log([1e-15])

array([-34.53877639])

In [22]:
y_predicted

array([1, 1, 0, 0, 1])

In [23]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [25]:
1 - epsilon

0.999999999999999

In [26]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [27]:
y_predicted_new = np.array(y_predicted_new)

In [28]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [29]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [30]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [31]:
log_loss(y_true, y_predicted)

ValueError: operands could not be broadcast together with shapes (6,) (5,) 