In [1]:
import numpy as np
from tensorflow import keras
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

In [2]:
reviews = [
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
one_hot('amazing restaurant',30)

[16, 26]

In [8]:
vocab_size = 30
encoded_review = [one_hot(d,vocab_size) for d in reviews]
encoded_review

[[21, 27],
 [16, 26],
 [19, 19],
 [27, 5, 6],
 [8, 24, 14],
 [26, 27],
 [25, 24, 13],
 [29, 25],
 [29, 11],
 [10, 25]]

In [9]:
max_length = 4
padded_reviews = pad_sequences(encoded_review,maxlen=max_length,padding='post')
padded_reviews

array([[21, 27,  0,  0],
       [16, 26,  0,  0],
       [19, 19,  0,  0],
       [27,  5,  6,  0],
       [ 8, 24, 14,  0],
       [26, 27,  0,  0],
       [25, 24, 13,  0],
       [29, 25,  0,  0],
       [29, 11,  0,  0],
       [10, 25,  0,  0]])

In [14]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [11]:
x = padded_reviews
y = sentiment

In [15]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 16)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 137 (548.00 Byte)
Trainable params: 137 (548.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.fit(x,y,epochs=50,verbose=0)

In [18]:
loss,accuracy = model.evaluate(x,y)

1/1 [==============================] - 0s 201ms/step - loss: 0.6131 - accuracy: 1.0000


In [19]:
model.get_layer('embedding').get_weights()[0]

array([[ 0.08070183,  0.02100974, -0.09067521, -0.07138447],
       [-0.0241501 ,  0.02152501,  0.04667092, -0.0364188 ],
       [-0.03058671, -0.04292606,  0.00089251,  0.01211164],
       [-0.00753539, -0.01043778, -0.04583782,  0.03842207],
       [ 0.00750222, -0.02659979, -0.01986915, -0.00264489],
       [-0.01901425, -0.02764039, -0.09041022, -0.02494902],
       [-0.07723352, -0.08533585,  0.02782264,  0.08545203],
       [ 0.02166306, -0.03293419,  0.01965311,  0.04867846],
       [-0.02185902, -0.09489334, -0.02579269,  0.03402081],
       [ 0.02628097, -0.02374624, -0.01039713,  0.02475027],
       [ 0.02978435,  0.03478578,  0.05500504, -0.0313365 ],
       [ 0.08205021, -0.01543639,  0.09714382,  0.09598676],
       [-0.04678925, -0.02341496, -0.04948578, -0.02303354],
       [ 0.06906294,  0.06224997, -0.094098  , -0.08290987],
       [-0.03646336, -0.00988923,  0.0724908 ,  0.06442767],
       [-0.03013436, -0.03198782,  0.01417762, -0.04618493],
       [-0.06214079, -0.

In [20]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [22]:
weights[21]

array([-0.1044681 , -0.0587201 , -0.0475878 ,  0.09216208], dtype=float32)

In [23]:
weights[16]

array([-0.06214079, -0.01267773, -0.04817935,  0.10543979], dtype=float32)