In [1]:
import numpy as np
from tensorflow import keras
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

In [2]:
reviews = [
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvemnt'
]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0,])

In [4]:
one_hot('amazing restaurant',30)

[13, 23]

In [6]:
vocab_size = 30
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[17, 28], [13, 23], [22, 14], [4, 13, 7], [7, 25, 9], [8, 28], [22, 25, 14], [9, 16], [9, 2], [17, 16]]


In [9]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
padded_reviews

array([[17, 28,  0,  0],
       [13, 23,  0,  0],
       [22, 14,  0,  0],
       [ 4, 13,  7,  0],
       [ 7, 25,  9,  0],
       [ 8, 28,  0,  0],
       [22, 25, 14,  0],
       [ 9, 16,  0,  0],
       [ 9,  2,  0,  0],
       [17, 16,  0,  0]])

In [16]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [17]:
x = padded_reviews
y = sentiment

In [18]:
model.compile(
    optimizer='adam',loss='binary_crossentropy',
    metrics=['accuracy']    
)

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 4)              120       
                                                                 
 flatten (Flatten)           (None, 16)                0         
                                                                 
 dense (Dense)               (None, 1)                 17        
                                                                 
Total params: 137 (548.00 Byte)
Trainable params: 137 (548.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.fit(x,y,epochs=50,verbose=0)

In [20]:
# evalute the model
loss,accuracy = model.evaluate(x,y)

1/1 [==============================] - 0s 176ms/step - loss: 0.6431 - accuracy: 1.0000


In [21]:
accuracy

1.0

In [22]:
model.get_layer('embedding').get_weights()[0]

array([[ 0.06324863, -0.10214502, -0.0674599 , -0.01046341],
       [ 0.04166177, -0.04825228,  0.0335428 ,  0.02081189],
       [ 0.07484444, -0.03466138, -0.10121329, -0.03888288],
       [-0.01926578, -0.04900428, -0.00195087, -0.03527943],
       [ 0.00266096, -0.00617511, -0.04770136, -0.00017559],
       [ 0.02263984, -0.04137061,  0.03193102, -0.04848539],
       [-0.03706175, -0.01925739,  0.00619365,  0.00801362],
       [ 0.01480985, -0.02463184,  0.05162015, -0.02208904],
       [-0.09213721,  0.00604849,  0.00613189,  0.08329204],
       [-0.08499371,  0.02318339,  0.0926804 ,  0.03779032],
       [ 0.00988166, -0.0165254 , -0.02372496,  0.03558811],
       [-0.04828534,  0.01890152, -0.02325821, -0.045688  ],
       [-0.01794291,  0.03389604,  0.03267975,  0.00656718],
       [-0.01582082, -0.08596742, -0.02820529,  0.02238765],
       [-0.0825067 ,  0.02945445, -0.07000019,  0.09354204],
       [ 0.00972728,  0.02857692,  0.04173404, -0.00930341],
       [ 0.0496726 , -0.

In [23]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [25]:
weights[17]

array([ 0.04652496, -0.04724308, -0.0172611 ,  0.01249396], dtype=float32)